---
# ---
# Database information
# ---

# SANDBOX
#DATABASES:
#    default:
#        ENGINE: django.db.backends.sqlite3
#        NAME: sandbox.db

## PRODUCTION
DATABASES:
    default:
        ENGINE: 'django.db.backends.mysql'
        NAME: 'pipeline'
        USER: 'pipeline001'
        PASSWORD: 'password'
        HOST: 'localhost'
        PORT: 3306

SECRET_KEY: ""

# Fernet keys
FERNET_KEYS: []

# JWT AUTH settings
JWT_AUTH:
    JWT_SECRET_KEY:
    JWT_ISSUER:
    JWT_AUDIENCE:
    JWT_VERIFY_AUDIENCE:

# ---
# AWS Buckets, Prefixes
# ---
# Studio/Platform
edx_s3_ingest_prefix:
edx_s3_ingest_bucket:
edx_s3_endpoint_bucket:

# CF
edx_cloudfront_prefix:

# Images
aws_video_images_bucket:
aws_video_images_prefix: "video-images/"


# VEDA Internal
veda_s3_upload_bucket:
veda_s3_hotstore_bucket:
veda_deliverable_bucket:
# Settings
veda_base_url:
s3_base_url: https://s3.amazonaws.com


# Transcripts
aws_video_transcripts_bucket:
aws_video_transcripts_prefix: video-transcripts/

# cielo24 api urls
cielo24_api_base_url: https://sandbox.cielo24.com/api

# 3playmedia api urls
three_play_api_base_url: https://api.3playmedia.com/
three_play_api_transcript_url: https://static.3playmedia.com/

# a token identifying a valid request from transcript provider
transcript_provider_request_token: testtoken

# Ingest Secret
# TODO: Elminate access key after AWS Support ticket 08/20/17 regarding cross-account IAM role access.
veda_secret_access_key:
veda_access_key_id:

# ---
# email vars
# ---
veda_noreply_email:
admin_email:

# ---
# VEDA API
# ---
## VEDA API Auth
veda_api_url:
veda_auth_url:
veda_client_id:
veda_secret_key:
veda_token_url:

# ---
# VAL
# ---
val_api_url:
val_token_url:
val_video_images_url:
# Credentials
val_client_id:
val_secret_key:
val_password:
val_username:
val_transcript_create_url:
val_video_transcript_status_url:

# Celery Worker Config Information
rabbitmq_broker:
rabbitmq_pass:
rabbitmq_user:

# ---
# Shotgun Variables (internal mediateam)
# ---
sg_server_path:
sg_script_name:
sg_script_key:

# ---
# Endpoints
# ---
threeplay_ftphost:
