---
# ---
# Database information
# ---
DATABASES:
    default:
        ENGINE: django.db.backends.sqlite3
        NAME: sandbox.db

SECRET_KEY: "a_random_string"

FERNET_KEYS: ["a_random_string"]

debug: True

# Frontend S3 Auth
veda_secret_access_key: A_RANDOM_STRING
veda_access_key_id: A_RANDOM_STRING

# JWT AUTH settings
JWT_AUTH:
  JWT_SECRET_KEY: A_RANDOM_STRING
  JWT_ISSUER:
  JWT_AUDIENCE: A_RANDOM_STRING
  JWT_VERIFY_AUDIENCE: true

# ---
# AWS
# ---
#veda_s3_upload_bucket:
#veda_s3_hotstore_bucket:
#veda_deliverable_bucket:
#veda_upload_bucket:
#edx_s3_ingest_prefix:
#edx_s3_ingest_bucket:
#edx_s3_endpoint_bucket:
#edx_cloudfront_prefix:
#aws_video_images_bucket:
#aws_video_images_prefix:

s3_base_url:
veda_base_url:

aws_video_transcripts_bucket:
aws_video_transcripts_prefix: video-transcripts/


# a token identifying a valid request from transcript provider
transcript_provider_request_token:

# ---
# email vars
# ---
veda_noreply_email: admin@example.com
admin_email: admin@example.com

lms_base_url:
instance_prefix: ''

# ---
# VAL user creds
# ---
val_token_url:
val_api_url:
val_video_images_url:
val_transcript_create_url:
val_video_transcript_status_url:
val_client_id:
val_secret_key:
val_username: admin@example.com
val_password:

## VEDA API Auth
veda_api_url:
veda_auth_url:
veda_client_id:
veda_secret_key:
veda_token_url:

# ---
# Celery Info
# ---
celery_app_name:
# can do multiple queues like so: foo,bar,baz
celery_worker_queue:
celery_deliver_queue:
celery_heal_queue:
celery_threads: 1

rabbitmq_broker:
rabbitmq_pass:
rabbitmq_user:

onsite_worker: False

# ---
# Shotgun Variables (internal mediateam)
# ---
sg_server_path:
sg_script_name:
sg_script_key:

...
